---
title: "Ds485"
author: "Emmet"
format: pdf
editor: visual
---

# Importing and Cleaning

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(janitor)

library(reshape2)
library(plotly)
library(magrittr)
library(tidyr)
library(RColorBrewer)
library(plyr)
library(stringr)
library(Hmisc)
library(qqplotr)
library(olsrr)
library(factoextra)
library(rsample)
library(caret)
library(rattle)
library(ggfortify)
library(glmnet)
```

```{r}
soccer <- read_csv("KPIs.csv") %>% clean_names()
```

```{r}
soccer <- soccer %>% mutate(formation = as.factor(formation))
```

```{r}
soccer <- soccer %>%
drop_na()
```

```{r}
head(soccer)
```

# EDA Begins

```{r}
ggplot(soccer, aes(x = attacking_clear_cuts , y = jc_goals)) + 
  geom_point() +
    xlab("Chances") +
  ylab("JC Goals") + 
  theme_bw()

#not really enough data to see anyhting, but there is a positive trend which makes sense
```

```{r}
cor(soccer$attacking_clear_cuts, soccer$jc_goals)
```

```{r}
ggplot(soccer, aes(x = opponent_clear_cuts , y = opponent_goals)) + 
  geom_point() +
    xlab("Opponents Chances") +
  ylab("Opponent Goals") + 
  theme_bw()
#not really enough data to see anyhting, but there is a positive trend which makes sense

```

```{r}
cor(soccer$opponent_clear_cuts, soccer$opponent_goals)
```

```{r}
ggplot(soccer, aes(x = opponent_clear_cuts , y = opponent_goals, size = massey_ranking)) + 
  geom_point() +
    xlab("Chances") +
  ylab("Opponent Goals") + 
  theme_bw()

#smaller number means the team is better. We gave up more chances and goals to the better teams
```

```{r}
ggplot(soccer, aes(x = opponent_clear_cuts , y = opponent_goals, shape = formation)) + 
  geom_point() +
    xlab("Chances") +
  ylab("Opponent Goals") + 
  theme_bw()

#Circle is the 352 and the triangle is 4231, we do not see much from this, especially without incorporating massey ranking because we played better teams while in a 352
```

```{r}
ggplot(soccer, aes(x = attacking_clear_cuts , y = jc_goals, shape = formation)) + 
  geom_point() +
    xlab("Chances") +
  ylab("JC Goals") + 
  theme_bw()

#Circle is the 352 and the triangle is 4231, we do not see much from this, especially without incorporating massey ranking because we played better teams while in a 352
```

```{r}
ggplot(soccer, aes(x = first_ball_percentage, y = second_ball_percentage)) + 
  geom_point() +
    xlab("First Ball Won Percentage") +
  ylab("Second Ball Won Percentage") + 
  theme_bw()

#minimal correlation between the amount of first balls and second balls won
```

```{r}
cor(soccer$first_ball_percentage, soccer$second_ball_percentage)
```

```{r}
ggplot(data = soccer) + 
  geom_histogram(mapping = aes(x = jc_goals)) + 
  theme_bw() 
```

```{r}
ggplot(data = soccer) + 
  geom_histogram(mapping = aes(x = opponent_goals)) + 
  theme_bw() 
```

```{r}
ggplot(data = soccer) + 
  geom_histogram(mapping = aes(x = opponent_goals, fill = formation)) + 
  theme_bw() +
    xlab("Opponent Goals") +
  ylab("Number of Games") + 
   scale_fill_discrete(labels= c("3-5-2", "4-2-3-1")) +
  theme_bw()
#hard to interpret without massey ranking but just shows the distribution better
```

```{r}
ggplot(data = soccer) + 
  geom_histogram(mapping = aes(x = jc_goals, fill = formation)) + 
   xlab("Juniata Goals") +
  ylab("Number of Games") + 
    scale_fill_discrete(labels= c("3-5-2", "4-2-3-1")) +
  
  theme_bw() 
#hard to interpret without massey ranking but just shows the distribution better. Got shutout way too much
```

```{r}
ggplot(soccer, aes(x = wide_attacks_total, y = attacking_clear_cuts)) + 
  geom_point() +
    xlab("Wide Attacks") +
  ylab("CLear Cuts") + 
  theme_bw()

#looks like wide attacks correlate with clear cuts, which again makes sense
```

```{r}
cor(soccer$wide_attacks_total, soccer$attacking_clear_cuts)
```

```{r}
ggplot(soccer, aes(x = wide_attacks_won, y = attacking_clear_cuts)) + 
  geom_point() +
    xlab("Wide Attacks") +
  ylab("CLear Cuts") + 
  theme_bw()
```

```{r}
cor(soccer$wide_attacks_won, soccer$attacking_clear_cuts)
```

```{r}
ggplot(soccer, aes(x = wide_attacks_percentage, y = attacking_clear_cuts)) + 
  geom_point() +
    xlab("Wide Attacks") +
  ylab("Clear Cuts") + 
  theme_bw()

#wide attacks percent is the least correlated with the clear cuts because if you ahve a bunch of wide attacks, you do not need to be as efficient.
```

```{r}
cor(soccer$wide_attacks_percentage, soccer$attacking_clear_cuts)
```

```{r}
ggplot(data = soccer) + 
  geom_boxplot(mapping = aes(x = opponent_clear_cuts, y = formation)) +
  scale_y_discrete(labels= c("3-5-2", "4-2-3-1")) +
  xlab("Opponent Clear Cut Chances") +
  ylab("Formation") + 
  theme_bw()

#very similar median, but spead and q1 and q3 are quite different. IQR is similar size though
```

```{r}
ggplot(data = soccer) + 
  geom_boxplot(mapping = aes(x = attacking_clear_cuts, y = formation)) +
  scale_y_discrete(labels= c("3-5-2", "4-2-3-1")) +
  xlab("Attacking Clear Cut Chances") +
  ylab("Formation") + 
  theme_bw()
#cannot look into too much because of quality of tea, but median again is similar
```

```{r}
ggplot(data = soccer) + 
  geom_boxplot(mapping = aes(x = jc_goals, y = formation)) +
  scale_y_discrete(labels= c("3-5-2", "4-2-3-1")) +
  xlab("Goals Scored") +
  ylab("Formation") + 
  theme_bw()
#First time with completely different median
```

```{r}
ggplot(data = soccer) + 
  geom_boxplot(mapping = aes(x = opponent_goals, y = formation)) +
  scale_y_discrete(labels= c("3-5-2", "4-2-3-1")) +
  xlab("Goals Given Up") +
  ylab("Formation") + 
  theme_bw()
#same median, different IQR and spread
```

```{r}
ggplot(data = soccer) + 
  geom_boxplot(mapping = aes(x = wide_attacks_total, y = formation)) +
  scale_y_discrete(labels= c("3-5-2", "4-2-3-1")) +
  xlab("Total Wide Attacks") +
  ylab("Formation") + 
  theme_bw()

#different median could be interesting to look into
```

```{r}
ggplot(data = soccer) + 
  geom_boxplot(mapping = aes(x = defensive_wide_attacks_percentage, y = formation)) +
  scale_y_discrete(labels= c("3-5-2", "4-2-3-1")) +
  xlab("Defensive Wide Attack Success Rate") +
  ylab("Formation") + 
  theme_bw()

#wide attacks seem to differ between the formations
```

```{r}
ggplot(data = soccer) + 
  geom_boxplot(mapping = aes(x = first_ball_percentage, y = formation)) +
  scale_y_discrete(labels= c("3-5-2", "4-2-3-1")) +
  xlab("First Balls Won Percentage") +
  ylab("Formation") + 
  theme_bw()

#first balls are quite similar but 352 has a smaller spread
```

```{r}
view(soccer)
```

```{r}
ggplot(soccer, aes(x = massey_ranking, y = first_ball_percentage, size = second_ball_percentage)) + 
  geom_point() +
    xlab("Massey Ranking") +
  ylab("First Ball Percentage") + 
  theme_bw()
```

```{r}
ggplot(soccer, aes(x = massey_ranking, y = defensive_wide_attacks_total, size = defensive_wide_attacks_percentage)) + 
  geom_point() +
    xlab("Massey Ranking") +
  ylab("Defensive Wide Attacks Total") + 
  theme_bw()
```

```{r}
soccer$result <- ifelse(soccer$jc_goals > soccer$opponent_goals, "W",
               ifelse(soccer$jc_goals < soccer$opponent_goals, "L", "T"))

view(soccer)
```

```{r}
ggplot(data = soccer) + 
  geom_boxplot(mapping = aes(x = attacking_clear_cuts, y = result)) +
  xlab("First Balls Won Percentage") +
  ylab("Result") + 
  theme_bw()
```

```{r}
ggplot(data = soccer) + 
  geom_boxplot(mapping = aes(x = opponent_clear_cuts, y = result)) +
  xlab("Opponent Clear Cuts") +
  ylab("Result") + 
  theme_bw()
```

```{r}
ggplot(data = soccer) + 
  geom_boxplot(mapping = aes(x = massey_ranking, y = result)) +
  xlab("Massey Ranking") +
  ylab("Result") + 
  theme_bw()
```

```{r}
ggplot(data = soccer) + 
  geom_bar(mapping = aes(x = result, fill = formation)) + 
  theme_bw() +
  scale_fill_discrete(labels=c("4-2-3-1", "3-5-2")) 
```

```{r}
ggplot(soccer, aes(x = opponent_clear_cuts , y = opponent_goals, color = result)) + 
  geom_point() +
    xlab("Chances") +
  ylab("Opponent Goals") + 
  theme_bw()
```

```{r}
ggplot(soccer, aes(x = attacking_clear_cuts , y = jc_goals, color = result)) + 
  geom_point() +
    xlab("Attacking Clear Cut Chances") +
  ylab("Juniata Goals") + 
  labs(color='Result') +
  
  theme_bw()
```

```{r}
ggplot(soccer, aes(x = wide_attacks_total , y = wide_attacks_won, color = result)) + 
  geom_point() +
    xlab("Wide Attacks") +
  ylab("Wide Attacks Won") + 
  theme_bw()
```

```{r}
ggplot(soccer, aes(x = defensive_wide_attacks_percentage, y = defensive_wide_attacks_total, color = result)) + 
  geom_point() +
    xlab("Defensive Wide Attacks Percentage") +
  ylab("Defensive Wide Attacks Total") + 
  theme_bw()
```

```{r}
ggplot(soccer, aes(x = massey_ranking, y = opponent_goals, color = result)) + 
  geom_point() +
    xlab("Massey Ranking") +
  ylab("Opponent Goals") + 
  labs(color='Result') +
  theme_bw()
```

```{r}
soccer <- mutate(soccer, corner_kicks_percentage = ifelse(corner_kicks_percentage == "#DIV/0!", NA, corner_kicks_percentage))

```

```{r}
soccer <- soccer%>% 
  mutate(corner_kicks_percentage = as.numeric(corner_kicks_percentage))
```

```{r}
view(soccer)
```

```{r}
# only using the athletes (heat map)
soccer_map <- soccer %>%   select(c(2:24, 26:36)) #all the numeric variables 

selectedcorr_mat <- round(cor(soccer_map),2)  

melted_corr_mat <- melt(selectedcorr_mat)

melted_corr_mat

```

```{r}

ggplot(data = melted_corr_mat,  aes(x=Var1, y=Var2, fill=value)) +   geom_tile() +  scale_fill_distiller(palette="RdBu",direction=-1,limits=c(-1,1))+ 
geom_text(aes(Var2, Var1, label = value), color = "black", size = 1)+
  #theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 5)) +
#theme(axis.text.y = element_text(angle = 0, hjust = 1, size = 4)) +
  scale_y_discrete(label= c(jc_goals = "Juniata Goals", opponent_goals = "Opponent Goals", jc_shots="Juniata Shots", opponent_shots = "Opponent Shots", massey_ranking = "Massey Ranking", won_off_backline="Won Off Backline", opponent_backline_to_frontline = "Opponent Transition", opponent_clear_cuts = "Opponent Clear Cut Chances", backline_to_frontline="Juniata Transition", attacking_clear_cuts = "Attacking Clear Cut Chances", box_touches = "Box Touches", corner_kicks_total="Total Corner Kicks", corner_kicks_unsuccessful="Unsuccessful Corner Kicks", corner_kicks_successful="Successful Corner Kicks", free_kicks_percentage = "Free Kick Percentage", free_kicks_total = "Total Free Kicks", free_kicks_unsuccessful = "Unsuccessful Free Kicks", free_kicks_successful = "Successful Free Kicks", defensive_wide_attacks_percentage = "Defensive Wide Attacks Percentage", defensive_wide_attacks_total = "Total Defensive Wide Area", defensive_wide_attacks_lost = "Defensive Wide Area Lost", defensive_wide_attacks_won = "Defensive Wide Attacks Won", wide_attacks_percentage = "Wide Attack Percentage", wide_attacks_total = "Total Wide Attacks", wide_attacks_lost = "Wide Attacks Lost", wide_attacks_won = "Wide Attacks Won", second_ball_percentage = "Second Ball Percentage", second_ball_total = "Total Second Balls", second_ball_lost = "Second Balls Lost", second_ball_won = "Second Balls Won", first_ball_percentage = "First Ball Percentage", first_ball_total = "Total First Balls", first_ball_lost = "First Balls Lost", first_ball_won = "First Balls Won")) +
  scale_x_discrete(label= c(jc_goals = "Juniata Goals", opponent_goals = "Opponent Goals", jc_shots="Juniata Shots", opponent_shots = "Opponent Shots", massey_ranking = "Massey Ranking", won_off_backline="Won Off Backline", opponent_backline_to_frontline = "Opponent Transition", opponent_clear_cuts = "Opponent Clear Cut Chances", backline_to_frontline="Juniata Transition", attacking_clear_cuts = "Attacking Clear Cut Chances", box_touches = "Box Touches", corner_kicks_total="Total Corner Kicks", corner_kicks_unsuccessful="Unsuccessful Corner Kicks", corner_kicks_successful="Successful Corner Kicks", free_kicks_percentage = "Free Kick Percentage", free_kicks_total = "Total Free Kicks", free_kicks_unsuccessful = "Unsuccessful Free Kicks", free_kicks_successful = "Successful Free Kicks", defensive_wide_attacks_percentage = "Defensive Wide Attacks Percentage", defensive_wide_attacks_total = "Total Defensive Wide Area", defensive_wide_attacks_lost = "Defensive Wide Area Lost", defensive_wide_attacks_won = "Defensive Wide Attacks Won", wide_attacks_percentage = "Wide Attack Percentage", wide_attacks_total = "Total Wide Attacks", wide_attacks_lost = "Wide Attacks Lost", wide_attacks_won = "Wide Attacks Won", second_ball_percentage = "Second Ball Percentage", second_ball_total = "Total Second Balls", second_ball_lost = "Second Balls Lost", second_ball_won = "Second Balls Won", first_ball_percentage = "First Ball Percentage", first_ball_total = "Total First Balls", first_ball_lost = "First Balls Lost", first_ball_won = "First Balls Won"))+  labs(x=NULL,y=NULL,fill=stringr::str_wrap("Correlation Coefficient",width=12))+  theme_bw() +  #theme( axis.text.x  = element_text(angle=90)) +
  theme(axis.text = element_text(size = 5),  # Set the size for both x and y axes
        axis.text.x = element_text(angle = 90))
```

```{r}
ggplot(soccer, aes(x = attacking_clear_cuts, y = opponent_clear_cuts, color = result)) + 
  geom_point() +
    xlab("Wide Attacks") +
  ylab("Wide Attacks Won") + 
  theme_bw()
```

```{r}

```
